ARROW-10390: [Rust][Parquet] Ensure it is possible to create custom parquet writers
As of https://github.com/apache/arrow/pull/8300, it no longer appears possible to implement a `ParquetWriter` to provide a custom writer because it is not possible to implement the trait as `TryClone` is not publicly exported.

This PR publically exports that trait and adds an end to end test demonstrating it is possible to create a custom writer

Here is what happens if you try and use `TryClone` on master

```
error[E0603]: module `util` is private
  --> delorean_parquet/src/writer.rs:11:5
   |
11 |     util::io::TryClone,
   |     ^^^^ private module
   |
note: the module `util` is defined here
  --> /Users/alamb/.cargo/git/checkouts/arrow-3a9cfebb6b7b2bdc/c148da1/rust/parquet/src/lib.rs:39:1
   |
39 | mod util;
   | ^^^^^^^^^

```

Closes #8528 from alamb/alamb/ARROW-10390-custom-parquet-writer

Authored-by: alamb <andrew@nerdnetworks.org>
Signed-off-by: Neville Dipale <nevilledips@gmail.com>